FROM python:3.12-slim AS consumer

WORKDIR /app

RUN pip install --no-cache-dir \
  pandas \
  kafka-python \
  boto3 \
  python-dotenv \
  pyarrow \
  requests

COPY src/ ./src/

CMD ["python", "-m", "src.streaming.consumer"]
