FROM python:3.12-slim AS producer

WORKDIR /app

RUN pip install --no-cache-dir \
  pandas \
  kafka-python \
  boto3 \
  python-dotenv \
  pyarrow

COPY src/ ./src/

CMD ["python", "-m", "src.streaming.producer"]
